development:
  driver: "mongoose" # Not used
  uri:    "mongodb://localhost/nodexpress3"
  debug:  false

production:
  driver: "mongoose" # Not used
  uri:    "mongodb://localhost/nodexpress3"
  debug:  false
