development:
  driver: "mongoose" # Not used
  uri:    "mongodb://localhost/nodexpress3"
  debug:  true

production:
  driver: "mongoose" # Not used
  uri:    "mongodb://localhost/nodexpress3"
  debug:  true
